export { default as About } from './About'
export { default as Home } from './Home'
export { default as NotFound } from './NotFound'
export { default as Service } from './Service'
export { default as Equipment } from './Equipment'
export { default as Thermos } from './Thermos'
export { default as SpecialProjects } from './SpecialProjects'
export { default as Bases } from './Bases'
